import { createRepo } from './repo'
import type { Task, Deadline, Link, Project, Snippet, Tool, Agent, Server, Domain, Backup, Habit, HabitLog, LedgerEntry, Pomodoro, HealthLog, Course, Assignment, Note, Pitfall, Resource, OpsFlow, OpsChange, OpsSecCheck, OpsSecret, OpsDnsRecord, Deployment, EnvVar, TechDebt, CmdSnippet, Decision, SkillNode, LearningPath, ThreeDProject, Portfolio, ContentCalendar, FixedBill, Grade, Flashcard, ReadQueueItem, FeynmanLog, Inspiration } from '../../drizzle/schema'

// 各模块 Repository 实例（跨模块表 + 核心表全覆盖）
export const tasksRepo = createRepo<Task>('tasks', ['title', 'scope', 'type', 'priority', 'projectId', 'status', 'dueDate', 'focusDate', 'note'], { timestamps: true })
export const deadlinesRepo = createRepo<Deadline>('deadlines', ['title', 'dueDate', 'source', 'sourceId', 'status', 'remindDays'])
export const linksRepo = createRepo<Link>('links', ['fromType', 'fromId', 'toType', 'toId', 'label'])
export const projectsRepo = createRepo<Project>('projects', ['name', 'description', 'status', 'techStack', 'repoPath'], { timestamps: true })
export const snippetsRepo = createRepo<Snippet>('snippets', ['title', 'language', 'code', 'description', 'tags'], { timestamps: true })
export const toolsRepo = createRepo<Tool>('tools', ['name', 'category', 'launchType', 'target', 'port', 'note', 'docUrl', 'hitCount'])
export const agentsRepo = createRepo<Agent>('agents', ['name', 'vendor', 'task', 'status', 'startedAt', 'note'])
export const serversRepo = createRepo<Server>('servers', ['name', 'purpose', 'vendor', 'region', 'ip', 'sshPort', 'user', 'config', 'monthlyCost', 'expireDate', 'status', 'note'])
export const domainsRepo = createRepo<Domain>('domains', ['name', 'registrar', 'dnsProvider', 'expireDate', 'serverId', 'sslExpireDate', 'cost', 'renewCycle', 'note'])
export const backupsRepo = createRepo<Backup>('backups', ['name', 'location', 'lastBackupAt', 'verified', 'note'])
export const habitsRepo = createRepo<Habit>('habits', ['name', 'color'])
export const habitLogsRepo = createRepo<HabitLog>('habitLogs', ['habitId', 'date'])
export const ledgerRepo = createRepo<LedgerEntry>('ledger', ['type', 'amount', 'category', 'note', 'date'])
export const pomodorosRepo = createRepo<Pomodoro>('pomodoros', ['task', 'minutes', 'startedAt', 'completed'])
export const healthLogsRepo = createRepo<HealthLog>('healthLogs', ['date', 'sleepHours', 'exerciseMin', 'mood', 'weight', 'note'])
export const coursesRepo = createRepo<Course>('courses', ['name', 'weekday', 'startPeriod', 'endPeriod', 'location', 'teacher', 'weeks', 'note'])
export const assignmentsRepo = createRepo<Assignment>('assignments', ['courseId', 'title', 'dueDate', 'status', 'note'])
export const notesRepo = createRepo<Note>('notes', ['title', 'content', 'tags', 'courseId'], { timestamps: true })
export const pitfallsRepo = createRepo<Pitfall>('pitfalls', ['title', 'category', 'problem', 'solution', 'tags'], { timestamps: true })
export const resourcesRepo = createRepo<Resource>('resources', ['title', 'url', 'category', 'note'])
export const opsFlowsRepo = createRepo<OpsFlow>('opsFlows', ['name', 'metric', 'threshold', 'current', 'status', 'note'], { timestamps: true })
export const opsChangesRepo = createRepo<OpsChange>('opsChanges', ['title', 'env', 'category', 'detail', 'operator', 'changedAt', 'status'])
export const opsSecChecksRepo = createRepo<OpsSecCheck>('opsSecChecks', ['title', 'category', 'severity', 'result', 'detail', 'checkedAt'])
export const opsSecretsRepo = createRepo<OpsSecret>('opsSecrets', ['name', 'provider', 'account', 'status', 'expiresAt', 'note'])
export const opsDnsRepo = createRepo<OpsDnsRecord>('opsDns', ['name', 'recordType', 'host', 'value', 'ttl', 'status', 'note'])
export const deploymentsRepo = createRepo<Deployment>('deployments', ['project', 'env', 'version', 'status', 'deployedAt', 'operator', 'note'])
export const envVarsRepo = createRepo<EnvVar>('envVars', ['key', 'value', 'scope', 'note'], { timestamps: true })
export const techDebtsRepo = createRepo<TechDebt>('techDebts', ['title', 'category', 'severity', 'project', 'status', 'detail'])
export const cmdSnippetsRepo = createRepo<CmdSnippet>('cmdSnippets', ['title', 'category', 'command', 'note', 'hitCount'])
export const decisionsRepo = createRepo<Decision>('decisions', ['title', 'context', 'decision', 'alternatives', 'status', 'decidedAt'])
export const skillTreeRepo = createRepo<SkillNode>('skillTree', ['name', 'parentId', 'level', 'status', 'note'])
export const learningPathsRepo = createRepo<LearningPath>('learningPaths', ['title', 'goal', 'step', 'resource', 'status', 'orderIndex'])
export const threeDProjectsRepo = createRepo<ThreeDProject>('threeDProjects', ['name', 'tool', 'category', 'status', 'path', 'note'])
export const portfoliosRepo = createRepo<Portfolio>('portfolios', ['title', 'category', 'url', 'path', 'status', 'note'])
export const contentCalendarsRepo = createRepo<ContentCalendar>('contentCalendars', ['title', 'platform', 'plannedAt', 'status', 'note'])
export const fixedBillsRepo = createRepo<FixedBill>('fixedBills', ['name', 'amount', 'category', 'cycle', 'dueDay', 'payMethod', 'status', 'note'])
export const gradesRepo = createRepo<Grade>('grades', ['courseId', 'courseName', 'examType', 'score', 'total', 'weight', 'date', 'note'])
export const flashcardsRepo = createRepo<Flashcard>('flashcards', ['front', 'back', 'deck', 'level', 'dueDate', 'lastReview', 'reviewCount'])
export const readQueueRepo = createRepo<ReadQueueItem>('readQueue', ['title', 'author', 'category', 'url', 'status', 'priority', 'totalPages', 'currentPage', 'rating', 'note', 'addedAt', 'finishedAt'])
export const feynmanLogsRepo = createRepo<FeynmanLog>('feynmanLogs', ['topic', 'explanation', 'gap', 'source', 'status'])
export const inspirationsRepo = createRepo<Inspiration>('inspirations', ['content', 'tags', 'mood', 'starred'], { timestamps: true })
